CREATE VIEW VIEW_JOIN_ANIMAL_PESSOA
AS
SELECT A.codigo, A.NOME 'NOME DO ANIMAL', 
	A.DATANASC 'DATA DE NASCIMENTO DO ANIMAL', 
	P.NOME 'NOME DO TUTOR', RACA FROM ANIMAL A
INNER JOIN PESSOA P ON P.codigo = A.COD_TUTOR;